# yaml-language-server: $schema=https://coderabbit.ai/integrations/schema.v2.json
language: "en-US"

reviews:
  profile: "chill"          # optional
  high_level_summary: true  # optional
  review_status: true       # optional

  auto_review:
    enabled: true
    drafts: false
    # 👇 THIS is the important part
    base_branches:
      - "dev"        # allow PRs targeting dev
      # or use ".*" to allow ALL non-default branches
      # - ".*"
